FROM apache/airflow:2.9.3-python3.9

USER airflow

# Pin airflow version and install all required providers/libraries
RUN pip install --no-cache-dir \
    "apache-airflow==2.9.3" \
    apache-airflow-providers-postgres \
    apache-airflow-providers-apache-kafka \
    kafka-python \
    psycopg2-binary \
    pandas \
    requests

USER root
COPY init-airflow.sh /init-airflow.sh
RUN chmod +x /init-airflow.sh
USER airflow
