FROM confluentinc/cp-kafka-connect:7.9.0

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

# HDFS 3.x Sink Connector (compatible con Apache Hadoop 3.4.x)
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs3:1.1.17
